In [3]:
# Python Version Check

import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.13.1 (main, Apr 30 2025, 11:41:46) [Clang 20.0.0git (https:/github.com/llvm/llvm-project 1d810ece2b2c8fab7772049386


In [6]:
# Difference between Mutable and Immutable Data Types.

# Mutable Data Type Example (List)
my_list = [2, 4, 8]
print("Original List:", my_list)

# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)

# Immutable Data Type Example (Tuple)
my_tuple = (2, 4, 8)
print("Original Tuple:", my_tuple)
#my_tuple.append(4)  Trying to modify the tuple (will raise an attribute error)


Original List: [2, 4, 8]
Modified List: [2, 4, 8, 4]
Original Tuple: (2, 4, 8)


In [7]:
# Data Types - Numeric

age = 20 #int
pi = 3.14 #float
temperature = -6.5 #float

print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))


data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [11]:
# Data Types - Sequence - String

name = "Alice"
greeting = 'Hello'
address = "123 Main St"

print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))

# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [12]:
# Data Types - Sequence - List

list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]

# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [14]:
# Data Types - Sequence - Tuple

colors = ('red', 'green', 'yellow', 'blue')

print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])

colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


<class 'TypeError'>: 'tuple' object does not support item assignment

In [16]:
# Data Types - Sequence - Dict

person = {'name':'John','age':30,'city':'Pittsburgh'}

print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {
person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [17]:
# Data Types - Set

unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [18]:
# Data Types - Boolean

is_student = True
has_license = False

print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [19]:
# Sample Code - if-else statement

num = 10

if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

Positive


In [20]:
# Sample Code - Comparision Operator

x = 5
y = 10

if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [21]:
# Sample Code - Logical Operator

# Define two boolean variables
a = True
b = False

# Using the and operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False") # This will be printed
    
# Using the or operator
if a or b:
    print("At least one of a or b is True") # This will be printed
else:
    print("Both a and b are False")
    
# Using the not operator
if not a:
    print("a is False") # This will not be printed
else:
    print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


In [2]:
# Sample Code - Various Loops

# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
    print(fruit)

# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1

# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
if fruit == "apple":
    break
    
# Continiue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
banana
orange


<class 'SyntaxError'>: 'break' outside loop (1452302980.py, line 20)

In [3]:
# Example on Built - in - Function

print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


In [7]:
# Example on Built - in - Methods

# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
print (message)

# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
print (fruits)

# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25
print (age)

HELLO
['apple', 'banana', 'cherry']
25


In [9]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.

    This function prompts the user to specify the conversion type
    (Celsius to Fahrenheit or Fahrenheit to Celsius) and then asks
    for the temperature value. It calculates and returns the
    converted temperature.

    Returns:
        float: The converted temperature value.
    """

    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")

    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")

    if choice == "1":
        # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}°C is equal to {fahrenheit}°F")
        return fahrenheit

    elif choice == "2":
        # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}°F is equal to {celsius}°C")
        return celsius

    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None


# Call the function
if __name__ == "__main__":
    temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius


Enter 1 or 2:  1
Enter temperature in Celsius:  36


36.0°C is equal to 96.8°F


TO DO TASK-----------------------------------------------------------------------------------------------------------------------------

4.1 Exercise on Functions:

In [10]:
# Task 1

def unit_converter():
    """
    Converts units of measurement for length, weight, and volume.

    The function asks the user to select the type of conversion and
    then enter a value. It performs the selected conversion and
    displays the result.

    Returns:
        float: The converted value.
    """

    print("Select the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter your choice (1-3): "))

        # Ask for value to convert
        value = float(input("Enter the value to convert: "))

        if choice == 1:
            print("Length Conversion Options:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            option = int(input("Enter your choice (1-2): "))

            if option == 1:
                result = value * 3.28084
                print(f"{value} meters = {result:.2f} feet")
                return result
            elif option == 2:
                result = value / 3.28084
                print(f"{value} feet = {result:.2f} meters")
                return result
            else:
                print("Invalid length conversion option.")

        elif choice == 2:
            print("Weight Conversion Options:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            option = int(input("Enter your choice (1-2): "))

            if option == 1:
                result = value * 2.20462
                print(f"{value} kg = {result:.2f} lbs")
                return result
            elif option == 2:
                result = value / 2.20462
                print(f"{value} lbs = {result:.2f} kg")
                return result
            else:
                print("Invalid weight conversion option.")

        elif choice == 3:
            print("Volume Conversion Options:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            option = int(input("Enter your choice (1-2): "))

            if option == 1:
                result = value * 0.264172
                print(f"{value} L = {result:.2f} gallons")
                return result
            elif option == 2:
                result = value / 0.264172
                print(f"{value} gallons = {result:.2f} L")
                return result
            else:
                print("Invalid volume conversion option.")

        else:
            print("Invalid conversion type.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")

    return None


# Call the function
unit_converter()

Select the type of conversion:
1. Length
2. Weight
3. Volume


Enter your choice (1-3):  1
Enter the value to convert:  10


Length Conversion Options:
1. Meters to Feet
2. Feet to Meters


Enter your choice (1-2):  2


10.0 feet = 3.05 meters


3.047999902464003

In [11]:
# Task 2

def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of the numbers in the list.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum number in a list.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The largest number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum number in a list.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The smallest number in the list.
    """
    return min(numbers)


def main():
    try:
        print("Choose an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter your choice (1-4): "))

        # User enters numbers separated by space
        user_input = input("Enter numbers separated by spaces: ")

        # Convert input into a list of floats
        numbers = [float(num) for num in user_input.split()]

        if len(numbers) == 0:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            result = calculate_sum(numbers)
            print("Sum:", result)

        elif choice == 2:
            result = calculate_average(numbers)
            print("Average:", result)

        elif choice == 3:
            result = find_maximum(numbers)
            print("Maximum:", result)

        elif choice == 4:
            result = find_minimum(numbers)
            print("Minimum:", result)

        else:
            print("Invalid operation choice.")

    except ValueError:
        print("Error: Please enter valid numeric values.")


# Run the program
main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter your choice (1-4):  4
Enter numbers separated by spaces:  2 5 8 1


Minimum: 1.0


4.2 Exercise on List Manipulation:

In [13]:
# Task 1 Extract Every Other Element:

def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element from the original list.
    """
    return lst[::2]

# Example
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Output:", result)

Output: [1, 3, 5]


In [14]:
# Task 2 Slice a Sublist:

def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from start index to end index (inclusive).

    Parameters:
        lst (list): The original list.
        start (int): Starting index.
        end (int): Ending index.

    Returns:
        list: Sublist from start to end.
    """
    return lst[start:end+1]


# Example
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


In [15]:
# Task 3 Reverse a List Using Slicing:

def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): The original list.

    Returns:
        list: Reversed list.
    """
    return lst[::-1]


# Example
print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


In [16]:
# Task 4 Remove the First and Last Elements:

def remove_first_last(lst):
    """
    Removes the first and last elements of a list.

    Parameters:
        lst (list): The original list.

    Returns:
        list: List without first and last elements.
    """
    return lst[1:-1]


# Example
print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


In [17]:
# Task 5 Get the First n Elements:

def get_first_n(lst, n):
    """
    Returns the first n elements of a list.

    Parameters:
        lst (list): The original list.
        n (int): Number of elements to extract.

    Returns:
        list: First n elements.
    """
    return lst[:n]


# Example
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


In [18]:
# Task 6 Extract Elements from the End:

def get_last_n(lst, n):
    """
    Returns the last n elements of a list.

    Parameters:
        lst (list): The original list.
        n (int): Number of elements to extract.

    Returns:
        list: Last n elements.
    """
    return lst[-n:]


# Example
print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


In [19]:
# Task 7 Extract Elements in Reverse Order:

def reverse_skip(lst):
    """
    Returns every second element in reverse order starting from the second-to-last element.

    Parameters:
        lst (list): The original list.

    Returns:
        list: Elements in reverse order skipping one each time.
    """
    return lst[-2::-2]


# Example
print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


4.3 Exercise on Nested List:

In [20]:
# Task 1 Flatten a Nested List:

def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): A nested list.

    Returns:
        list: A flattened list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result


# Example
print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


In [21]:
# Task 2 Accessing Nested List Elements

def access_nested_element(lst, indices):
    """
    Accesses an element from a nested list using a list of indices.

    Parameters:
        lst (list): Nested list.
        indices (list): List of indices to access the element.

    Returns:
        element: The element at the specified position.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element


# Example
lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst, [1,2]))

6


In [22]:
# Task 3 Sum of All Elements in a Nested List

def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    Parameters:
        lst (list): Nested list.

    Returns:
        int/float: Sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# Example
print(sum_nested([[1,2],[3,[4,5]],6]))

21


In [23]:
# Task 4 Remove Specific Element from a Nested List

def remove_element(lst, elem):
    """
    Removes all occurrences of an element from a nested list.

    Parameters:
        lst (list): Nested list.
        elem: Element to remove.

    Returns:
        list: Modified list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


# Example
print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


In [24]:
# Task 5 Find the Maximum Element in a Nested List

def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
        lst (list): Nested list.

    Returns:
        int/float: Maximum element.
    """
    max_value = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)

    return max_value


# Example
print(find_max([[1,2],[3,[4,5]],6]))

6


In [26]:
def count_occurrences(lst, elem):
    """
    Counts how many times an element appears in a nested list.

    Parameters:
        lst (list): Nested list.
        elem: Element to count.

    Returns:
        int: Number of occurrences.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count


# Example
print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


In [27]:
# Task 7 Deep Flatten (Any Depth)

def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
        lst (list): Deeply nested list.

    Returns:
        list: Flattened list.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result


# Example
print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


In [28]:
# Task 8 Nested List Average

def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): Nested list.

    Returns:
        float: Average value.
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


# Example
print(average_nested([[1,2],[3,4],[5,6]]))

3.5


10.1 Basic Vector and Matrix Operation with Numpy.

Problem 1: Array Creation

In [29]:
# Initialize an empty array (2×2)

import numpy as np

arr = np.empty((2,2))
print(arr)

[[ 2.21353023e-307 -2.79469014e+050]
 [ 5.21698646e+257  2.56930068e+151]]


In [31]:
# Initialize an all ones array (4×2)

arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
# Create array filled with a value

arr = np.full((3,3), 5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [33]:
# Zeros array with same shape as another array

a = np.array([[1,2],[3,4]])
arr = np.zeros_like(a)
print(arr)

[[0 0]
 [0 0]]


In [34]:
# Ones array with same shape as another array

a = np.array([[1,2],[3,4]])
arr = np.ones_like(a)
print(arr)

[[1 1]
 [1 1]]


In [35]:
# Convert list to NumPy array

new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


Problem 2: Array Manipulation

In [36]:
# Array values from 10 to 49

arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [37]:
# Create 3×3 matrix from 0 to 8

arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
# Create 3×3 identity matrix

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# Random array size 30 and mean

arr = np.random.random(30)
print(arr.mean())

0.4745969133868124


In [40]:
# 10×10 random array with min and max

arr = np.random.random((10,10))
print("Min:", arr.min())
print("Max:", arr.max())

Min: 0.011325451273583864
Max: 0.9957630965299122


In [41]:
# Replace 5th element with 1

arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
# Reverse array

arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

[0 4 0 0 2 1]


In [43]:
# 2D array with 1 on border

arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
# 8×8 checkerboard pattern

arr = np.zeros((8,8),dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3: Array Operations

In [45]:
# Define arrays

import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [46]:
# Add arrays
print(x + y)

[[ 6  8]
 [10 13]]


In [47]:
# Subtract arrays
print(x - y)

[[-4 -4]
 [-4 -3]]


In [48]:
# Multiply array by integer
print(x * 3)

[[ 3  6]
 [ 9 15]]


In [49]:
# Square of each element
print(x ** 2)

[[ 1  4]
 [ 9 25]]


In [50]:
# Dot products
print("v.w =", np.dot(v,w))
print("x.v =", np.dot(x,v))
print("x.y =", np.dot(x,y))

v.w = 219
x.v = [29 77]
x.y = [[19 22]
 [50 58]]


In [51]:
# Concatenate arrays
print(np.vstack((x,y)))
print(np.column_stack((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [52]:
# Concatenate x and v (error explanation)
# Error occurs because x is 2D and v is 1D, so their dimensions do not match.

print(np.concatenate((x,v)))

<class 'ValueError'>: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem 4: Matrix Operations

In [53]:
# Define matrices
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
# Prove A·A⁻¹ = I

A_inv = np.linalg.inv(A)
print(np.dot(A,A_inv))

In [54]:
# Prove AB ̸= BA.

print("AB =")
print(np.dot(A,B))

print("BA =")
print(np.dot(B,A))

AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]


In [55]:
# Prove (AB)ᵀ = BᵀAᵀ

left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("Left:", left)
print("Right:", right)

Left: [[23 51]
 [13 29]]
Right: [[23 51]
 [13 29]]


In [56]:
# Solve Linear Equation System

import numpy as np

A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

X = np.dot(np.linalg.inv(A), B)

print("Solution:", X)

Solution: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

1. Element-wise Addition

In [60]:
# Python Lists

import time

# create lists
a = list(range(1000000))
b = list(range(1000000))

start = time.time()

result = [a[i] + b[i] for i in range(len(a))]

end = time.time()

print("Time taken using Python Lists:", end - start)

Time taken using Python Lists: 0.2610001564025879


In [61]:
# NumPy Arrays

import numpy as np
import time

a = np.arange(1000000)
b = np.arange(1000000)

start = time.time()

result = a + b

end = time.time()

print("Time taken using NumPy:", end - start)

Time taken using NumPy: 0.0410001277923584


2. Element-wise Multiplication

In [62]:
# Python Lists

import time

a = list(range(1000000))
b = list(range(1000000))

start = time.time()

result = [a[i] * b[i] for i in range(len(a))]

end = time.time()

print("Time taken using Python Lists:", end - start)

Time taken using Python Lists: 0.3819999694824219


In [63]:
# NumPy Arrays

import numpy as np
import time

a = np.arange(1000000)
b = np.arange(1000000)

start = time.time()

result = a * b

end = time.time()

print("Time taken using NumPy:", end - start)

Time taken using NumPy: 0.04399991035461426


3. Dot Product

In [64]:
import time

a = list(range(1000000))
b = list(range(1000000))

start = time.time()

dot = sum(a[i] * b[i] for i in range(len(a)))

end = time.time()

print("Dot product:", dot)
print("Time taken using Python Lists:", end - start)

Dot product: 333332833333500000
Time taken using Python Lists: 0.5260000228881836


In [65]:
import numpy as np
import time

a = np.arange(1000000)
b = np.arange(1000000)

start = time.time()

dot = np.dot(a, b)

end = time.time()

print("Dot product:", dot)
print("Time taken using NumPy:", end - start)

Dot product: 584144992
Time taken using NumPy: 0.003000020980834961


4. Matrix Multiplication

In [ ]:
import time

# create matrices
A = [[1]*1000 for _ in range(1000)]
B = [[1]*1000 for _ in range(1000)]

start = time.time()

result = [[sum(A[i][k] * B[k][j] for k in range(1000)) 
          for j in range(1000)] 
          for i in range(1000)]

end = time.time()

print("Time taken using Python Lists:", end - start)

In [ ]:
import numpy as np
import time

A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()

result = np.dot(A, B)

end = time.time()

print("Time taken using NumPy:", end - start)

Kernel Interrupt: Interrupted